pub struct GmailApiQuota {
    pub drafts_create: usize,
    pub drafts_delete: usize,
    pub drafts_get: usize,
    pub drafts_list: usize,
    pub drafts_send: usize,
    pub drafts_update: usize,
    pub get_profile: usize,
    pub history_list: usize,
    pub labels_create: usize,
    pub labels_delete: usize,
    pub labels_get: usize,
    pub labels_list: usize,
    pub labels_update: usize,
    pub messages_attachments_get: usize,
    pub messages_batch_delete: usize,
    pub messages_delete: usize,
    pub messages_get: usize,
    pub messages_import: usize,
    pub messages_insert: usize,
    pub messages_list: usize,
    pub messages_modify: usize,
    pub messages_send: usize,
    pub messages_trash: usize,
    pub messages_untrash: usize,
    pub settings_delegates_create: usize,
    pub settings_delegates_delete: usize,
    pub settings_delegates_get: usize,
    pub settings_delegates_list: usize,
    pub settings_filters_create: usize,
    pub settings_filters_delete: usize,
    pub settings_filters_get: usize,
    pub settings_filters_list: usize,
    pub settings_forwarding_addresses_create: usize,
    pub settings_forwarding_addresses_delete: usize,
    pub settings_forwarding_addresses_get: usize,
    pub settings_forwarding_addresses_list: usize,
    pub settings_get_auto_forwarding: usize,
    pub settings_get_imap: usize,
    pub settings_get_pop: usize,
    pub settings_get_vacation: usize,
    pub settings_send_as_create: usize,
    pub settings_send_as_delete: usize,
    pub settings_send_as_get: usize,
    pub settings_send_as_list: usize,
    pub settings_send_as_update: usize,
    pub settings_send_as_verify: usize,
    pub settings_update_auto_forwarding: usize,
    pub settings_update_imap: usize,
    pub settings_update_pop: usize,
    pub settings_update_vacation: usize,
    pub stop: usize,
    pub threads_delete: usize,
    pub threads_get: usize,
    pub threads_list: usize,
    pub threads_modify: usize,
    pub threads_trash: usize,
    pub threads_untrash: usize,
    pub watch: usize,
}

pub const GMAIL_QUOTA_PER_SECOND: usize = 250;

pub const GMAIL_API_QUOTA: GmailApiQuota = GmailApiQuota {
    drafts_create: 10,
    drafts_delete: 10,
    drafts_get: 5,
    drafts_list: 5,
    drafts_send: 100,
    drafts_update: 15,
    get_profile: 1,
    history_list: 2,
    labels_create: 5,
    labels_delete: 5,
    labels_get: 1,
    labels_list: 1,
    labels_update: 5,
    messages_attachments_get: 5,
    messages_batch_delete: 50,
    messages_delete: 10,
    messages_get: 5,
    messages_import: 25,
    messages_insert: 25,
    messages_list: 5,
    messages_modify: 5,
    messages_send: 100,
    messages_trash: 5,
    messages_untrash: 5,
    settings_delegates_create: 100,
    settings_delegates_delete: 5,
    settings_delegates_get: 1,
    settings_delegates_list: 1,
    settings_filters_create: 5,
    settings_filters_delete: 5,
    settings_filters_get: 1,
    settings_filters_list: 1,
    settings_forwarding_addresses_create: 100,
    settings_forwarding_addresses_delete: 5,
    settings_forwarding_addresses_get: 1,
    settings_forwarding_addresses_list: 1,
    settings_get_auto_forwarding: 1,
    settings_get_imap: 1,
    settings_get_pop: 1,
    settings_get_vacation: 1,
    settings_send_as_create: 100,
    settings_send_as_delete: 5,
    settings_send_as_get: 1,
    settings_send_as_list: 1,
    settings_send_as_update: 100,
    settings_send_as_verify: 100,
    settings_update_auto_forwarding: 5,
    settings_update_imap: 5,
    settings_update_pop: 100,
    settings_update_vacation: 5,
    stop: 50,
    threads_delete: 20,
    threads_get: 10,
    threads_list: 10,
    threads_modify: 10,
    threads_trash: 10,
    threads_untrash: 10,
    watch: 100,
};
