[package]
name = "gen-key"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[[bin]]
name = "gen-key"
path = "src/main.rs"

[dependencies]
# -- App Crates
lib-utils = { path = "../../libs/lib-utils"}
# -- Others
rand = "0.8"