[package]
name = "decrypt"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "decrypt"
path = "src/main.rs"

[dependencies]
dotenvy = "0.15.7"
lib-utils = { path = "../../libs/lib-utils"}

[lints]
workspace = true
