version: "3.9"
services:
  mailclerk-server:
    container_name: mailclerk-server
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    image: mailclerk-server:amd64
  mailclerk-server-macos:
    container_name: mailclerk-server
    platform: linux/arm64
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    image: mailclerk-server:arm64
