//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod cleanup_settings;
pub mod email_training;
pub mod processed_daily_summary;
pub mod processed_email;
pub mod sea_orm_active_enums;
pub mod user;
pub mod user_account_access;
pub mod user_token_usage_stats;
