//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod processed_daily_summary;
pub mod processed_email;
pub mod user_session;
pub mod user_settings;
pub mod user_token_usage_stats;
