//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::email_training::Entity as EmailTraining;
pub use super::processed_daily_summary::Entity as ProcessedDailySummary;
pub use super::processed_email::Entity as ProcessedEmail;
pub use super::user_session::Entity as UserSession;
pub use super::user_settings::Entity as UserSettings;
pub use super::user_token_usage_stats::Entity as UserTokenUsageStats;
