//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "processed_email")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_session_id: i32,
    pub user_session_email: String,
    pub processed_at: DateTimeWithTimeZone,
    pub labels_applied: Vec<String>,
    pub labels_removed: Vec<String>,
    pub ai_answer: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_session::Entity",
        from = "Column::UserSessionEmail",
        to = "super::user_session::Column::Email",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserSession2,
    #[sea_orm(
        belongs_to = "super::user_session::Entity",
        from = "Column::UserSessionId",
        to = "super::user_session::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserSession1,
}

impl ActiveModelBehavior for ActiveModel {}
